### PR TITLE
Logo Rounded Edges

### PR DESCRIPTION
**Pull request by IllicitMoonshine**
Edges have been rounded to 25 radius

### CODE REVIEW

**Review by IllicitMoonshine — COMMENTED** [review]
Updated logo.

**Review by IllicitMoonshine — COMMENTED** [review]
Logo changed.

**Comment by 0dminnimda** [comment]
Thanks for the pr!

I think you downloaded the SVG as a PNG (or any other bitmap), modified it, and then converted the image back to SVG. Unfortunately, in this way SVG has lost its meaning - to be as scalable as you want it to be.

I would recommend that you look at [`logo_raw.svg`](https://github.com/0dminnimda/pynalyser/blob/main/docs/logo_raw.svg), modify it, and then commit. And yes, if you don't have the right font, it will look weird, but that's ok.
I don't require you to, but if you want, you can download the font form [here](https://github.com/0dminnimda/pynalyser/files/8401913/LIBRARY.3.AM.zip) and then use inkscape's "Path > Object to Path" function to make `logo.svg` from `logo_raw.svg`. (`logo.svg` is used as a logo)

**Comment by 0dminnimda** [comment]
Hey, this PR was not touched for some time, if you still want to finish this work, I will be glad to hear about it! In any case, thanks for the effort!
I will close this PR for now, and if you tell me that you want to continue to work, I will immediately reopen it!

**Pull request closed without merging**
